In [4]:
import numpy as np

In [7]:
# arange creates an array of ints
a1 = np.arange(8)
# arange can have start, stop and step interval args
a2 = np.arange(3, 10, 2)

In [8]:
print(a1)
print(a2)
# Shape prop gives us details on the array like what rank the nested arrays are and how long
print(a1.shape)
print(a2.shape)

[0 1 2 3 4 5 6 7]
(8,)
[3 5 7 9]
(4,)


In [10]:
# zeros method generates an array with a given number of zeros
a3 = np.zeros(3)
print(a3);

[0. 0. 0.]


In [11]:
# zeros method can also generate 2d arrays of zeros like so 

In [12]:
a4 = np.zeros((2,4));
print(a4);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# full method generates arrays like zeros() but fills it with the arg element
a5 = np.full((2,1), 7)
print(a5)

[[7]
 [7]]


In [15]:
# The eye method generates a 2d array with 1s going diagonally across the rows
a6 = np.eye(6)
print(a6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [16]:
# Random method used to generate an array of random values
a7 = np.random.random((2,4))
print(a7)

[[0.45861025 0.63932095 0.82924551 0.21354766]
 [0.92756059 0.00753873 0.61636425 0.49980633]]


In [17]:
# Use a python list to generate an array
sampleList = [1, 2, 3]
r1 = np.array(sampleList)
print(r1)

[1 2 3]


In [18]:
# Access is similar to a python list 
print(r1[1])

2


In [24]:
# You can also generate a 2d array from lists 
r2 = np.array([sampleList, [1,2, 4]])
print(r2)
print(r2.shape)

[[1 2 3]
 [1 2 4]]
(2, 3)


In [27]:
# Access is similar 
print(r1[[0, 2]])

[1 3]


In [28]:
# Boolean indexing can be used to check which index passes a condition 

In [30]:
print(r1>2)
print(r1[r1 > 2])

[False False  True]
[3]


In [32]:
# If you want all elements that pass a different condition use the same pattern
nums = np.arange(20)
print(nums[nums % 2 ==0])

[ 0  2  4  6  8 10 12 14 16 18]


In [39]:
# How to slice a 2d array
newArr = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(newArr);

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [42]:
# The first arg in the slice is the rows or outer arrays and the second arg is the columns or contents of each list 
b1 = newArr[0:2, :2]
print(b1);

[[1 2]
 [1 2]]


In [46]:
# Negative indices also work and step backwards from the end of each respective list 
b2 = newArr[:-1, :-2]
print(b2)

[[1 2 3]
 [1 2 3]]


In [49]:
# Slices are only references to the original list 
# Modifications to the b2 reference are applied to the original array. 
b2[0, 2] = 6
print(newArr)

[[1 2 6 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [50]:
# The shapes of slices depend on how you slice them
b3 = newArr[2:, :]
b4 = newArr[2, :]
print(b3.shape)
print(b4.shape)

(1, 5)
(5,)


In [56]:
# Reshape lets you reshape an array like the previous rank 1 converting to a rank 2 or vice versa
print(b4)
b4 = b4.reshape(1, -1)
print(b4)

print(b3)
b3 = b3.reshape(-1 , )
print(b3)

[[1 2 3 4 5]]
[[1 2 3 4 5]]
[1 2 3 4 5]
[1 2 3 4 5]


In [60]:
# How to perform array math using numpy 
x1 = np.array([[1,2,3], [1,2,3]])
y1 = np.array([[4,5,6], [4,5,6]])

print(x1 + y1)

[[5 7 9]
 [5 7 9]]


In [62]:
# A common use of array math is in use of vectors
x1 = np.array([1, 3])
y1 = np.array([1, 1])
result = x1 + y1
print(result)

[2 4]


In [63]:
# the other operators also work
print(x1 - y1)
print(x1 * y1)
print(x1 / y1)

[0 2]
[1 3]
[1. 3.]


In [64]:
# Practical use example 
names = np.array(['seb', 'mich', 'ren'])
heights = np.array([1.90, 1.4, 2.1])
weights = np.array([100, 110, 120])